#----------------------------
# GitHub Action Part-1 Basics
#----------------------------

name: My-GitHabActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs: 
  my_testing:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
      
    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2.0"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

    - name: List current folder
      run : ls -la

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List current folder
      run : ls -la
      
  my_deploy: 
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "This is Job Lebel Variable1"
      VAR2 : "This is Job Lebel Variable2.0"

    steps:
    - name: Print Hello Message in Deploy
      run : echo "Hello World from Deploy job"

    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Super local Environment variable"

    - name: Printing Deploy packege
      run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

    - name: Lets test some packages if they are here 1
      run : aws --version

    - name: Lest test some packages if they are here 2
      run : zip --version
      

      
